directory-sources:
  list:
    -
      name: src1
      path: 'src:src1;src:src2'
      exclude: '**/*.md;**/dirtest'
directory-destination: 'dest:'

# values : zip, 7zip no (default)
compress: 7zip

#crypt: false
#password:

decrypt-sources: 'dest:backup_20220228_194834'

# path to 7zip
#path-sevenzip:

volume-size: 1g


