directory-sources:
  list:
    -
      name: src1
      path: 'src:src1;src:src2'
      exclude: '**/*.md;**/dirtest'
directory-destination: 'dest:'

#password:

decrypt-sources: 'dest:backup_20220228_194834'
